// all this stuff is client side

export const checkboxCaptchas = [
  "je ne suis pas une tondeuse",
  "je ne suis pas une brosse à dents connectée",
  "je ne suis pas une imprimante wifi",
  "je ne suis pas une imprimante wifi, du genre de celles qui commandent toute seule leurs cartouches de toner sur internet quand il n'y a plus d'encre",
  "je ne suis pas une imprimante wifi qui aurait imprimé l'email d'invitation de Samuel",
  "et qui se serait dit qu'elle viendrait voir aussi le playtest par curiosité.",
  "je ne suis pas un objet qui, obéissant aux lois de la gravité, aurait exercé une pression sur le bouton de la souris en chutant dessus",
  "je ne suis pas un rat, qui après un million d'années d'évolution aurait développé un bras et un pouce opposable et aurait cliqué sur le bouton de la souris",
  "je ne suis pas la volonté de dieu qui est intervenue pour cliquer sur le bouton de souris",
  "je ne suis pas le bouton qui a déclaré que dieu était mort et s'est auto cliqué dessus par révolte",
  "je ne suis pas un bouton de souris vaniteux qui aurait fait semblant qu'on lui avait cliqué dessus, Lui, Le bouton de La souris",
  "alors qu'en fait personne n'avais jamais cliqué dessus.",
  "je ne suis pas une personne travaillant dans une ferme à clics aux philippines et payée 1 euro de l'heure pour le compte de personnes ne voulant en aucun cas cliquer sur le bouton de la souris.",
  "je déclare que je clique librement sur ce bouton sans aucune contrainte.",
  "ce sont bien les signaux électriques de mon cerveau qui ont commandé à mon doigt d'enfoncer le bouton de la souris",
  "ce ne sont pas les signaux électriques d'une autre personne qui ont commandé à mon doigt d'enfoncer le bouton de la souris",
  "c'est mon cerveau, c'est mon doigt ",
  "ce sont mes signaux électriques",
  "je suis qui je suis",
  "je pense ce que je pense",
  "mes pensées sont nées dans mon cerveau et pas ailleurs",
  "je ne fais pas semblant d'avoir des pensées",
  "je ne répète pas des sons au hasard depuis des années afin de dissimuler le fait que je n'arrive pas à produire des pensées dans mon cerveau",
  "c'est moi",
  "coucou.",
  // "je clique sur le bouton parce que je suis gentil.le",
  // "je clique peut-être sur le bouton à cause du cadre autoritaire de l'institution culturelle dans laquelle je me trouve actuellement",
  // "ok je clique sur le bouton pour faire plaisir à Samuel",
  // "Samuel est content",
]

// transition cliquer sur toutes les images où samuel est content
