export const samuelText = {
  acte1: [
    [
      "Bonjour!",
      "C'est moi Samuel.",
      "Approchez, n'ayez pas peur",
      "Si vous n'arrivez pas bien à vous repérer parmi la foule c'est normal.",
      "Le pointeur de souris n'a pas été conçu comme une interface multijoueur.",
      "Est-ce que vous pourriez vous rassembler devant moi?",
      "",
    ],
    ["", "ouais en fait j'aime pas trop que vous soyez tous en face", "on dirait un cours en amphi", "est-ce que vous pourriez essayer de faire un cercle autour de moi?", ""],
    [
      "",
      "arf j'aime pas vraiment la vibe pardon",
      "ça fait un peu trop... je sais pas",
      "rituel?",
      "peut-être que si on... enfin si vous...",
      "si vous pouviez rajouter des angles droits à ce cercle",
      "peut-être que ce serait mieux? merci vous êtes sympas.",
      "",
    ],
    ["", "ou alors sinon", "on pourrait mettre des repères au sol", ""],
    ["", "et alors vous pourriez vous placer sur l'axe en fonction de vos revenus?", "au milieu j'ai mis le salaire net médian en 2022 à titre de comparaison.", ""],
    ["", "on peut essayer d'autres styles de classifications aussi", "du genre", ""],
    ["", "ou alors je sais pas, pourquoi pas ça sinon", ""],
    ["", "hmmm", "hm.", ""],
    [
      "",
      "bref",
      "pour en revenir au pointeur de souris",
      "que vous êtes",
      "et que je suis.",
      "saviez-vous que le pointeur de souris a été inventé en 1968?",
      "on peut donc dire que la souris d'ordinateur est plus jeune que ma mère",
      "puisque ma mère est née en 1957.",
      "ma mère, Michèle Planche.",
      "Avant que Douglas Englebart",
      "né en 1925",
      "n'invente la souris d'ordinateur",
      "il n'était pas possible de pointer",
      "il n'était pas possible de glisser-déposer",
      "il n'était pas possible de scroller",
      "il n'était pas possible de cliquer sur la roulette de sa souris",
      "il n'était pas possible de double-cliquer",
      "il n'était pas possible de simple-cliquer",
      "il n'était pas possible de passer ses nerfs sur la souris en cliquant plus fort que nécéssaire ou plus vite que nécéssaire.",
      "il était bien sûr possible d'insulter son ordinateur ou le jeter par la fenêtre",
      "de prendre le clavier et de taper sur l'écran avec violence",
      "de mettre un coup de pied dans l'ordinateur",
      "d'arracher les touches du clavier",
      "de mordre le cable d'alimentation",
      "de claquer le côté du moniteur cathodique",
      "de prendre une paire de ciseaux et de découper méticuleusement la disquette 3 pouces.",
      "d'un autre côté,",
      "Il était bien sûr possible de communiquer avec son ordinateur,",
      "mais il fallait pour ça utiliser un outil professionnel muni d'un trop grand nombre de touches",
      "le clavier.",
      "ma grand-mère est née en 1929",
      "donc après Douglas Englebart mais avant ma mère.",
      "les premiers ordinateurs sont nés dans les années 40",
      "donc après ma grand-mère mais avant ma mère.",
      "et après le début de la seconde guerre mondiale.",
      "née en 1939.",
      "la seconde guerre mondiale fut la cause principale du développement de l'informatique",
      "parce qu'il fallait casser les codes que les nazis utilisaient pour syncroniser leurs attaques sur les convois dans l'Atlantique",
      "notamment.",
      "s'il n'y avais pas eu l'informatique",
      "disent les conservateurs des musées sur l'informatique",
      "qui sont à la fois les personnes les mieux placées pour tenir ce genre de propos, mais qui sont également certainement les personnes qui ont le plus intérêt à éxagérer l'utilité des ordinateurs en général",
      "les ordinateurs ont raccourci la guerre de 1, 2 ou 4 ans, disent-ils.",
      "sans les ordinteurs, nous n'aurions pas gagné la guerre, ajouta Churchill.",
      "né en 1874.",
      "d'autres personnes prétendent que les ordinateurs n'ont servi à rien",
      "et ne serviront d'ailleurs jamais à rien.",
      "mais ces personnes exagèrent sans doute.",
      "s'il n'y avait pas eu la guerre ou s'il n'y avait pas eu ma grand-mère",
      "je ne serais pas actuellement devant vous en train de parler de l'histoire de l'informatique.",
      "mais assez parlé.",
      "le playtest touche a sa fin",
      "dans la dernière séquence de cette présentation,",
      "je vais venir vous chercher",
      "cachez-vous parce que si j'arrive à vous toucher,",
      "ça provoquera votre mort.",
      "",
    ],
    ["", "", ""],
  ],
}

// Bonjour. La souris d'ordinateur est plus jeune que ma mère puisqu'elle est née en 1968. Ma mère, quant à elle, est née en 1958. Avant que Douglas Engelbart, né en xxxx, n'invente la souris d'ordinateur, il n'était pas possible de cliquer, il n'était pas possible de pointer, il n'était pas possible de glisser-déposer, il n'était pas possible de scroller, il n'était pas possible de cliquer avec la roulette de la souris, il n'était pas possible de double-cliquer, il n'était pas possible de simple-cliquer, il n'était pas possible de passer ses nerfs sur la souris en cliquant plus fort que nécessaire ou plus vite que nécessaire.

// Il était bien sûr possible d'insulter son ordinateur ou de le jeter par la fenêtre, de prendre le clavier et de taper sur l'écran avec violence, de mettre un coup de pied dans l'ordinateur, d'arracher les touches du clavier, de mordre le câble d'alimentation, de claquer le côté du moniteur cathodique, de prendre une paire de ciseaux et de découper méticuleusement la disquette 3 pouces. Il était bien sûr possible de communiquer avec son ordinateur, mais il fallait pour ça utiliser un outil professionnel muni d'un trop grand nombre de touches, le clavier.

// Ma grand-mère est née en xxxx. Le tout premier ordinateur est né en xxxx
